### ISSUE TITLE
Use this library as dependency of Spring Cloud Config Server

### ISSUE THREAD

**Issue by fiunchinho** [zalando/spring-cloud-config-aws-kms#40]
I want to configure a Spring Cloud Config Server using a git backend. This git repository is under authentication, using username and password, so I'd like to encrypt these credentials using KMS, and make the application (the config server) to decrypt these values on bootstrap using KMS.
But if I try to start the config server I get

```
Caused by: org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'org.springframework.security.crypto.encrypt.TextEncryptor' available: expected single matching bean but found 2: defaultTextEncryptor,kmsTextEncryptor
```

is there a workaround?

**Comment by harti2006** [comment]
Hi, I reproduced your issue: Including both `spring-cloud-config-server` and `spring-cloud-config-aws-kms` always leads to the duplicate bean issue.
The offending bean is created at [DefaultTextEncryptorConfiguration](https://github.com/spring-cloud/spring-cloud-config/blob/v1.4.3.RELEASE/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/config/EncryptionAutoConfiguration.java#L138).
Unfortunately, the `@ConditionalOnMissingBean` annotation on that class does not work at all, probably because it is explicitly [@Imported](https://github.com/spring-cloud/spring-cloud-config/blob/v1.4.3.RELEASE/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/config/EncryptionAutoConfiguration.java#L57).
So far I was only able to get rid of the error by marking the KmsTextEncryptor as `@Primary` bean, which I think is a huge code smell.

I will upload my code to reproduce the case tomorrow and would open an issue in the Spring Cloud project.

**Comment by fiunchinho** [comment]
Thanks for taking a look. So currently there is no workaround for this :(

**Comment by harti2006** [comment]
@fiunchinho I did some more experiments and I think I found an easy solution for your problem: Please make sure to declare the dependency on `spring-cloud-config-aws-kms` before `spring-cloud-config-server` in your pom.xml. This should make sure that the KMS TextEncryptor is created before the DefaultTextEncryptor.

**Comment by fiunchinho** [comment]
I didn't know the order in my pom.xml would change the order in which the beans are created by Spring. That seems odd! I'll test it whenever I can. Thanks

**Comment by harti2006** [comment]
@fiunchinho Did you already have the chance to test the fix? If you can confirm the behavior, I would like to add a FAQ section in the README.

**Comment by harti2006** [comment]
@fiunchinho hi, just pinging if you already had the chance to verify my assumptions?

**Comment by dharezlak** [comment]
Hi, I just hit the same issue and I can confirm that ordering dependencies in the jar as suggested fixes the problem.

**Comment by harti2006** [comment]
Alright, thanks for confirmation. I will a note about it to the README....

**Comment by harti2006** [comment]
Also with the new project setup, it should be possible to create an integration test case for exactly this scenario as a separate maven module
